name: Deploy to Azure
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CreAITe'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

    - name: Configure Web App Settings
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config set --resource-group your-resource-group --name CreAITe --linux-fx-version "PYTHON|3.12"
          az webapp config appsettings set --resource-group your-resource-group --name CreAITe --settings \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true \
            FLASK_APP=app.py 